Use an env variable if set

diff --git a/cli b/cli
--- a/cli
+++ b/cli
@@ -1,5 +1,9 @@
 #!/bin/bash
-file="./cli.properties"
+if [ -z ${JENKINS_CLI_CONFIG} ]; then
+  file="./cli.properties"
+else
+  file=$JENKINS_CLI_CONFIG
+fi
 
 if [ -f "$file" ]
 then
@@ -7,7 +11,6 @@ then
 
   while IFS='=' read -r key value
   do
-    key=$(echo $key | tr '.' '_')
     eval "${key}='${value}'"
   done < "$file"
 
@@ -16,7 +19,8 @@ then
   echo "URL        = " $url
   echo ""
 else
-  echo "$file not found."
+  echo "Configuration file [$file] not found."
+  exit 1
 fi
 
 if [ ! -f jenkins-cli.jar ]; then
